version: '3.8'
services:
  breadlab:
    build:
      context: .
      dockerfile: Dockerfile
    #   target: base
    volumes:
      - ./:/app/
      - ./nodemon.json:/app/nodemon.json
    container_name: api-sms
    expose:
      - '3011'
    ports:
      - '3011:3011'
    command: npm run dev